In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [3]:
text = """경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오늘 말이 곱다\n"""

In [5]:
t = Tokenizer()
t.fit_on_texts([text])
vocab_size = len(t.word_index)+1

print('단어 집합의 크기 : %d' %vocab_size)

단어 집합의 크기 : 12


In [6]:
print(t.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오늘': 10, '곱다': 11}


In [11]:
sequences = list()
for line in text.split('\n'):
    encoded = t.texts_to_sequences([line])[0]
    print(encoded)
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)
        

print(sequences)
print('학습에 사용할 샘플의 수 : %d' %len(sequences))

[2, 3, 1, 4, 5]
[]
[6, 1, 7]
[]
[8, 1, 9, 10, 1, 11]
[]
[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]
학습에 사용할 샘플의 수 : 11


In [13]:
max_len = max(len(l) for l in sequences)
print('샘플의 최대 길이:%d'%max_len)

샘플의 최대 길이:6


In [14]:
sequences = pad_sequences(sequences, maxlen = max_len, padding='pre')

In [15]:
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [16]:
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]


In [17]:
print(X)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]


In [18]:
print(y)

[ 3  1  4  5  1  7  1  9 10  1 11]


In [19]:
y = to_categorical(y, num_classes=vocab_size)

In [20]:
y

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [21]:
#model setting
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [22]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
1/1 - 0s - loss: 2.4512 - accuracy: 0.0909
Epoch 2/200
1/1 - 0s - loss: 2.4356 - accuracy: 0.1818
Epoch 3/200
1/1 - 0s - loss: 2.4195 - accuracy: 0.2727
Epoch 4/200
1/1 - 0s - loss: 2.4027 - accuracy: 0.2727
Epoch 5/200
1/1 - 0s - loss: 2.3853 - accuracy: 0.2727
Epoch 6/200
1/1 - 0s - loss: 2.3672 - accuracy: 0.3636
Epoch 7/200
1/1 - 0s - loss: 2.3482 - accuracy: 0.3636
Epoch 8/200
1/1 - 0s - loss: 2.3285 - accuracy: 0.3636
Epoch 9/200
1/1 - 0s - loss: 2.3078 - accuracy: 0.3636
Epoch 10/200
1/1 - 0s - loss: 2.2863 - accuracy: 0.3636
Epoch 11/200
1/1 - 0s - loss: 2.2640 - accuracy: 0.3636
Epoch 12/200
1/1 - 0s - loss: 2.2408 - accuracy: 0.3636
Epoch 13/200
1/1 - 0s - loss: 2.2169 - accuracy: 0.3636
Epoch 14/200
1/1 - 0s - loss: 2.1923 - accuracy: 0.3636
Epoch 15/200
1/1 - 0s - loss: 2.1673 - accuracy: 0.3636
Epoch 16/200
1/1 - 0s - loss: 2.1421 - accuracy: 0.3636
Epoch 17/200
1/1 - 0s - loss: 2.1169 - accuracy: 0.3636
Epoch 18/200
1/1 - 0s - loss: 2.0922 - accuracy: 0.3636
E

Epoch 147/200
1/1 - 0s - loss: 0.4036 - accuracy: 0.8182
Epoch 148/200
1/1 - 0s - loss: 0.3989 - accuracy: 0.8182
Epoch 149/200
1/1 - 0s - loss: 0.3943 - accuracy: 0.8182
Epoch 150/200
1/1 - 0s - loss: 0.3897 - accuracy: 0.8182
Epoch 151/200
1/1 - 0s - loss: 0.3852 - accuracy: 0.8182
Epoch 152/200
1/1 - 0s - loss: 0.3808 - accuracy: 0.8182
Epoch 153/200
1/1 - 0s - loss: 0.3765 - accuracy: 0.8182
Epoch 154/200
1/1 - 0s - loss: 0.3722 - accuracy: 0.8182
Epoch 155/200
1/1 - 0s - loss: 0.3680 - accuracy: 0.8182
Epoch 156/200
1/1 - 0s - loss: 0.3638 - accuracy: 0.8182
Epoch 157/200
1/1 - 0s - loss: 0.3598 - accuracy: 0.8182
Epoch 158/200
1/1 - 0s - loss: 0.3557 - accuracy: 0.9091
Epoch 159/200
1/1 - 0s - loss: 0.3517 - accuracy: 0.9091
Epoch 160/200
1/1 - 0s - loss: 0.3478 - accuracy: 0.9091
Epoch 161/200
1/1 - 0s - loss: 0.3439 - accuracy: 0.9091
Epoch 162/200
1/1 - 0s - loss: 0.3401 - accuracy: 0.9091
Epoch 163/200
1/1 - 0s - loss: 0.3363 - accuracy: 0.9091
Epoch 164/200
1/1 - 0s - loss: 

In [25]:
def sentence_generation(model, t, current_word, n):
    init_word = current_word
    sentence = ''
    for _ in range(n):
        encoded = t.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=5, padding='pre')
        result = model.predict_classes(encoded, verbose=0)
        
        for word, index in t.word_index.items():
            if index == result:
                break
        current_word = current_word + ' ' + word
        sentence = sentence + ' ' + word
    sentence = init_word + sentence
    return sentence
        

In [26]:
print(sentence_generation(model, t, '경마장에', 4))

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
경마장에 있는 말이 뛰고 있다


In [27]:
print(sentence_generation(model, t, '그의', 2))

그의 말이 법이다


In [32]:
print(sentence_generation(model, t, '가는', 5))

가는 말이 고와야 오늘 말이 곱다
